version: '3.8'

services:
  # 1. MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: company_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

  # 2. Redis
  redis:
    image: redis:alpine
    container_name: company_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge