version: '3.8'

services:
  # 1. MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: company_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./db_data:/var/lib/mysql
    # [중요] expose -> ports로 변경해야 내 컴퓨터(IntelliJ)에서 접속 가능
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

  # 2. Redis
  redis:
    image: redis:alpine
    container_name: company_redis
    # [중요] 내 컴퓨터(Spring Boot)에서 접속 가능하도록 포트 개방
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge